version: "2"
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: hercules
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: hercules
      MYSQL_PASSWORD: hercules
    volumes:
      - ./persistence/mysql:/var/lib/mysql
    networks:
      - net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7.9-1
    depends_on:
      - "mysql"
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mysql
      - PMA_PORT=3306
    restart: always
    networks:
      - net
#   loginserver:
#     image: anpandu/hercules:0.0.1
#     depends_on:
#       - "mysql"
#     ports:
#       - 6900:6900
#     command: sh -c "./login-server.sh"
#     restart: always
#     networks:
#       - net
#   charserver:
#     image: anpandu/hercules:0.0.1
#     depends_on:
#       - "mysql"
#       - "loginserver"
#     ports:
#       - 6121:6121
#     command: sh -c "./char-server.sh"
#     restart: always
#     networks:
#       - net
#   mapserver:
#     image: anpandu/hercules:0.0.1
#     depends_on:
#       - "mysql"
#       - "loginserver"
#       - "charserver"
#     ports:
#       - 5121:5121
#     command: sh -c "./map-server.sh"
#     restart: always
#     networks:
#       - net
networks:
  net:
    driver: bridge