version: "2"
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: hercules
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: hercules
      MYSQL_PASSWORD: hercules
    volumes:
      - ./persistence/mysql:/var/lib/mysql
    networks:
      - net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7.9-1
    depends_on:
      - "mysql"
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mysql
      - PMA_PORT=3306
    restart: always
    networks:
      - net
networks:
  net:
    driver: bridge